name: Test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: formal-verification/lake-packages
        key: "${{ env.LAKE_VERSION }}"
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: Build
      run: go build
    - name: Test
      run: go test